/* Regenbogen-Kapelle: nachvollziehbare Lernwege mit lokalen Zwischenständen. */
(function(){
'use strict';
var D=AdventureData,C=AdventureCore,KEY='regenbogen_kapelle_v6',currentRoom=1,storageOkay=true;
function el(tag,cls,text){var e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function button(text,fn,cls){var b=el('button',cls||'btn',text);b.type='button';b.addEventListener('click',fn);return b;}
function fresh(){return {version:4,solved:{},progress:{},route:'all',custom:[],room:1};}
var state=fresh();try{var raw=JSON.parse(localStorage.getItem(KEY));if(raw&&raw.version===4&&raw.solved&&raw.progress&&typeof raw.progress==='object'){state=Object.assign(fresh(),raw);D.stations.forEach(function(s){if(state.solved[s.id]!==true)delete state.solved[s.id];});}}catch(e){}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){storageOkay=false;}var s=document.getElementById('saveStatus');if(s)s.textContent=storageOkay?'Zwischenstand auf diesem Gerät gespeichert.':'Speichern ist hier nicht möglich. Lasst diese Seite geöffnet.';}
if(!Array.isArray(state.custom))state.custom=[];if(!['all','short','custom'].includes(state.route))state.route='all';
function required(){if(state.route==='short')return D.shortRoute;if(state.route==='custom'){var a=state.custom.filter(function(id){return D.stations.some(function(s){return s.id===id;});});return a.length?a:D.shortRoute;}return D.stations.map(function(s){return s.id;});}
function allDone(){return D.stations.every(function(s){return state.solved[s.id];});}
function refresh(){var total=D.stations.filter(function(s){return state.solved[s.id];}).length,route=required(),done=route.filter(function(id){return state.solved[id];}).length;document.body.classList.toggle('restored',allDone());document.getElementById('progress').textContent=done+' / '+route.length+' Stationen eures Wegs · insgesamt '+total+' / 11';if(window.KapelleBonus)window.KapelleBonus.refresh();}
function screen(name){['intro','game','final'].forEach(function(n){document.getElementById(n).hidden=n!==name;});document.body.classList.remove('in-exercise');refresh();}
function focusHeading(root){var h=root.querySelector('h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo({top:0,behavior:'instant'});}
function progress(id){var p=state.progress[id];if(!p||typeof p!=='object'||!Number.isInteger(p.index)||p.index<0||p.index>20||!Array.isArray(p.answers)||!Array.isArray(p.engraved)){p={index:0,answers:[],engraved:[],burden:3,errors:0,reply:null,order:[],previous:-1,deck:[],mode:null,penalized:false};state.progress[id]=p;}p.burden=Math.max(0,Math.min(5,Number(p.burden)||0));return p;}
function start(){screen('game');showRoom(state.room===2?2:1);}
document.getElementById('startBtn').addEventListener('click',start);
document.getElementById('resetBtn').addEventListener('click',function(){if(confirm('Alle Spielstände auf diesem Gerät zurücksetzen?')){state=fresh();save();screen('intro');}});
document.getElementById('routeBtn').addEventListener('click',routeDialog);
document.getElementById('introRoute').addEventListener('click',routeDialog);
document.getElementById('roomOne').addEventListener('click',function(){showRoom(1);});document.getElementById('roomTwo').addEventListener('click',function(){showRoom(2);});
document.getElementById('finalBtn').addEventListener('click',finale);
document.getElementById('returnBtn').addEventListener('click',start);
function dialog(title,build){var d=el('dialog','book-dialog'),h=el('h2','',title),origin=document.activeElement;d.appendChild(button('Schließen ×',function(){d.close();},'btn book-close'));d.appendChild(h);build(d);document.body.appendChild(d);d.addEventListener('close',function(){d.remove();if(origin&&origin.isConnected)origin.focus({preventScroll:true});});d.showModal();d.querySelector('button').focus();return d;}
function book(){dialog('Das alte Buch',function(d){d.appendChild(el('p','','Wir lernen über die Zehn Gebote in lutherischer Zählung. Andere jüdische und christliche Traditionen zählen teilweise anders. Die folgenden Texte sind vereinfacht und sinngemäß, keine wörtlichen Bibelzitate.'));
var context=el('details');context.open=true;context.appendChild(el('summary','','Worum geht es?'));context.appendChild(el('p','','In der biblischen Erzählung führt Gott Israel aus der Sklaverei in Ägypten. Danach stehen die Gebote für das Leben mit Gott und miteinander. Sie gehören zur jüdischen Tora und werden auch im Christentum gelesen.'));d.appendChild(context);
D.book.forEach(function(g){var item=el('details');item.appendChild(el('summary','',g.n+' · '+D.commandments[g.n-1].label));item.appendChild(el('p','',g.text));item.appendChild(el('p','','Damals: '+g.then));item.appendChild(el('p','','Ein Beispiel heute: '+g.now));d.appendChild(item);});
var love=el('details');love.open=currentRoom===2;love.appendChild(el('summary','','Das Doppelgebot der Liebe'));love.appendChild(el('p','','Sinngemäß nach Matthäus 22,34–40: Ein Gesetzeslehrer fragt Jesus nach dem wichtigsten Gebot. Jesus verbindet Gottesliebe und Nächstenliebe: Liebe Gott mit deinem ganzen Leben und deinen Mitmenschen wie dich selbst. Beide Sätze stammen aus der Tora (Deuteronomium 6,5 und Levitikus 19,18).'));love.appendChild(el('p','','Eine hilfreiche Sicht: Die Gebote 1–3 beziehen sich unmittelbar auf Gott, 4–10 auf das Zusammenleben. Diese Schwerpunkte hängen zusammen.'));d.appendChild(love);
d.appendChild(el('p','','Zum Sorgenweg: Gefühle sind keine Fehler. Ratschläge können entlasten, müssen aber nicht jede Sorge lösen. Hilfe und Grenzen sind erlaubt. Erzählt nur persönliche Dinge, die ihr erzählen möchtet. Bei Angst, Drohungen oder Gewalt: Holt eine vertraute erwachsene Person dazu.'));
d.appendChild(el('h3','','Quellen zum Nachlesen'));[['Bibeltext Matthäus 22','https://www.die-bibel.de/bibel/LU17/MAT.22'],['Zehn Gebote und Zählung · EKD','https://www.ekd.de/islam/Zehn-Gebote-10802.htm'],['Wissenschaftlicher Hintergrund · WiBiLex','https://www.die-bibel.de/stichwort/10637'],['Elterngebot · WiBiLex','https://www.die-bibel.de/stichwort/17460']].forEach(function(x){var a=el('a','source-link',x[0]);a.href=x[1];a.target='_blank';a.rel='noopener noreferrer';d.appendChild(a);});});}
function routeDialog(){dialog('Lernweg auswählen',function(d){d.appendChild(el('p','','Mit der Lehrkraft auswählen. Beide Räume sind immer zugänglich. Der gewählte Weg bestimmt euer Zwischenziel; das große Fenster wird erst nach allen elf Stationen vollständig repariert.'));
[['all','Ganzes Abenteuer · 11 Stationen'],['short','Kurzweg · 6 Stationen, etwa 20–30 Minuten Spielzeit'],['custom','Eigene Auswahl']].forEach(function(x){var l=el('label','route-choice'),input=el('input');input.type='radio';input.name='route';input.value=x[0];input.checked=state.route===x[0];l.appendChild(input);l.appendChild(document.createTextNode(x[1]));d.appendChild(l);});var list=el('div','route-list');D.stations.forEach(function(s){var l=el('label'),check=el('input');check.type='checkbox';check.value=s.id;check.checked=state.custom.includes(s.id);l.appendChild(check);l.appendChild(document.createTextNode(s.title));list.appendChild(l);});d.appendChild(list);var open=el('label','route-choice bonus-teacher'),openBox=el('input');openBox.type='checkbox';openBox.checked=!!(state.bonus&&state.bonus.teacherOpen);open.appendChild(openBox);open.appendChild(document.createTextNode('🎁 Bonusspiele sofort freigeben (z. B. zum Ausprobieren)'));d.appendChild(open);var note=el('p','feedback');d.appendChild(note);d.appendChild(button('Lernweg übernehmen',function(){if(!state.bonus||typeof state.bonus!=='object')state.bonus={};state.bonus.teacherOpen=openBox.checked;var route=d.querySelector('input[name=route]:checked').value,chosen=Array.from(list.querySelectorAll('input:checked')).map(function(e){return e.value;});if(route==='custom'&&!chosen.length){note.textContent='Wählt mindestens eine Station aus.';return;}state.route=route;state.custom=chosen;save();d.close();if(!document.getElementById('game').hidden)showRoom(currentRoom);else refresh();},'btn sunshine'));});}
function showRoom(n){screen('game');currentRoom=n;state.room=n;save();var box=document.getElementById('roomContent');box.replaceChildren();box.className='card room-card room-'+n;box.appendChild(el('h2','',n===1?'Raum 1 · Die Zehn Gebote':'Raum 2 · Liebe im Alltag'));box.appendChild(el('p','','Wählt eine Station. Ihr könnt jederzeit unterbrechen und später weitermachen.'));
var grid=el('div','hotspot-grid');box.appendChild(grid);var b=button('Das alte Buch',book,'hotspot hotspot-info');b.dataset.station='buch';b.prepend(el('div','hotspot-icon','📖'));grid.appendChild(b);
D.stations.filter(function(s){return s.room===n;}).forEach(function(s){var t=button('',function(){openStation(s);},'hotspot '+(state.solved[s.id]?'hotspot-done':'hotspot-open'));t.dataset.station=s.id;t.appendChild(el('div','hotspot-icon',s.icon));t.appendChild(el('div','hotspot-label',s.title));t.appendChild(el('small','station-meta',s.time+' · '+(required().includes(s.id)?'Euer Lernweg':'Zusatzstation')));if(state.solved[s.id])t.appendChild(el('span','station-state','✓ Geschafft · nachlesen'));else if(state.progress[s.id])t.appendChild(el('span','station-state','↪ Fortsetzen'));grid.appendChild(t);});
var route=required();if(route.every(function(id){return state.solved[id];})){var done=el('div','route-success');done.appendChild(el('h3','','Euer Lernweg ist geschafft!'));done.appendChild(el('p','','Tauscht euch aus: Welche Entscheidung war schwierig? Begründet ein Beispiel mit einem Gebot.'));done.appendChild(button(allDone()?'Zur strahlenden Kapelle':'Unser Ergebnis ansehen',finale,'btn sunshine'));if(window.KapelleBonus)done.appendChild(button('🎁 Bonusspiele entdecken',window.KapelleBonus.show,'btn ghost'));box.appendChild(done);}focusHeading(box);}
function finaleStage(all){var stage=el('div','finale-stage'),cam=el('div','finale-camera');stage.appendChild(cam);var pic=el('img','finale-before');pic.src=all?'assets/kapelle.png':'assets/kapelle-kaputt.png';pic.alt=all?'Das reparierte Fenster leuchtet in allen Farben.':'Das Fenster wartet auf weitere reparierte Teile.';cam.appendChild(pic);if(!all)return stage;cam.appendChild(el('div','finale-glow'));stage.appendChild(button('↻ Nochmal ansehen',finaleCinema,'finale-replay'));if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)requestAnimationFrame(finaleCinema);return stage;}
function finaleCinema(){var old=document.querySelector('.finale-cinema');if(old)old.remove();var box=el('div','finale-cinema'),cam=el('div','finale-camera');box.setAttribute('role','img');box.setAttribute('aria-label','Das Fenster der Kapelle wird wieder ganz und leuchtet in allen Farben.');box.appendChild(cam);var before=el('img','finale-before');before.src='assets/kapelle-kaputt.png';before.alt='';var after=el('img','finale-after');after.src='assets/kapelle.png';after.alt='';cam.appendChild(before);cam.appendChild(after);cam.appendChild(el('div','finale-rays'));cam.appendChild(el('div','finale-glow'));var sparks=el('div','finale-sparkles'),colors=['#ff5a5f','#ffb000','#ffe45c','#4fd18b','#3fb7ff','#7a6bff','#ff7ad9'];for(var i=0;i<46;i++){var sp=el('span','');sp.style.setProperty('--x',(30+Math.random()*40).toFixed(1)+'%');sp.style.setProperty('--dx',(Math.random()*50-25).toFixed(1)+'vw');sp.style.setProperty('--dy',(Math.random()*70-15).toFixed(1)+'vh');sp.style.setProperty('--c',colors[i%colors.length]);sp.style.setProperty('--d',(3.4+Math.random()*4).toFixed(2)+'s');sp.style.setProperty('--t',(2.2+Math.random()*1.8).toFixed(2)+'s');sp.style.setProperty('--s',(8+Math.random()*12).toFixed(0)+'px');sparks.appendChild(sp);}box.appendChild(sparks);var closed=false;function close(){if(closed)return;closed=true;document.removeEventListener('keydown',key);box.classList.add('closing');setTimeout(function(){box.remove();var h=document.querySelector('#finalContent h2');if(h&&h.focus)h.focus();},800);}function key(e){if(e.key==='Escape'||e.key==='Enter'||e.key===' '){e.preventDefault();close();}}var skip=button('Überspringen ⏭',close,'finale-skip');box.appendChild(skip);box.addEventListener('click',function(e){if(e.target!==skip)close();});cam.addEventListener('animationend',function(e){if(e.animationName==='finale-camera')setTimeout(close,900);});document.addEventListener('keydown',key);document.body.appendChild(box);void box.offsetWidth;box.classList.add('play');skip.focus();}
function finale(){screen('final');var box=document.getElementById('finalContent');box.replaceChildren();var all=allDone();box.appendChild(finaleStage(all));box.appendChild(el('h2',all?'finale-text':'',all?'Die Kapelle erstrahlt!':'Euer Zwischenstand'));var route=required(),n=route.filter(function(id){return state.solved[id];}).length;box.appendChild(el('p',all?'finale-text':'',n+' von '+route.length+' Stationen eures Lernwegs sind fertig. '+(all?'Alle elf Stationen sind gelöst.':'Für das ganze Fenster könnt ihr später die übrigen Stationen ergänzen.')));box.appendChild(el('p','','Partnergespräch: Nennt eine hilfreiche Handlung und erklärt, warum sie zu einem Gebot passt. Ihr müsst keine persönlichen Sorgen erzählen.'));if(window.KapelleBonus)box.appendChild(button('🎁 Zu den Bonusspielen',window.KapelleBonus.show,'btn ghost'));focusHeading(box);}
function openStation(s){document.body.classList.add('in-exercise');var box=document.getElementById('roomContent');box.replaceChildren();box.className='card exercise-card';var toolbar=el('div','exercise-toolbar');toolbar.appendChild(button('← Raum',function(){showRoom(s.room);},'btn ghost'));toolbar.appendChild(button('📖 Altes Buch',book,'btn book-quick'));box.appendChild(toolbar);var area=el('section','exercise');area.dataset.station=s.id;box.appendChild(area);area.appendChild(el('h2','',s.title));area.appendChild(el('p','exercise-intro',s.intro));var body=el('div','exercise-body');area.appendChild(body);
var p=progress(s.id);function draw(){var wasInside=body.contains(document.activeElement);body.replaceChildren();renderStation(s,p,body,draw);if(wasInside){var target=body.querySelector('.feedback + button')||body.querySelector('.question,.selected-card,.mountain-statement,h3');if(target){if(target.tagName!=='BUTTON')target.tabIndex=-1;target.focus();}}}if(state.solved[s.id]&&!p.replaying){summary(s,body,function(){state.progress[s.id]={index:0,answers:[],engraved:[],burden:3,errors:0,reply:null,order:[],previous:-1,deck:[],mode:null,penalized:false,replaying:true};save();openStation(s);});}else draw();focusHeading(area);}
function finish(s,p,root){state.solved[s.id]=true;p.replaying=false;save();refresh();root.replaceChildren();summary(s,root,function(){p.index=0;p.answers=[];p.engraved=[];p.burden=3;p.reply=null;p.errors=0;p.order=[];p.deck=[];p.mode=null;p.replaying=true;save();openStation(s);});}
function summary(s,root,replay){root.appendChild(el('h3','','✓ Station geschafft'));var msgs={sorgenweg:'Ihr habt hilfreiche nächste Schritte gefunden. Sorgen im echten Leben dürfen bleiben und Unterstützung brauchen.',bergpruefung:'Ihr habt alle zehn Gebote geprüft. Die Zählung folgt hier der lutherischen Tradition.',werkstatt:'Beschreiben, Gefühle ausdrücken, Verantwortung übernehmen und Wiedergutmachung anbieten. Niemand muss sofort verzeihen.',bruecke:'Einladen, beim Lernen helfen und Grenzen achten können Brücken bauen.',sortieren:'Alle zehn Gebote sind geordnet. Gottesliebe und Nächstenliebe gehören zusammen.'};root.appendChild(el('p','feedback',msgs[s.id]||'Ihr habt die Entscheidungen begründet. Das alte Buch bleibt zum Nachlesen erreichbar.'));var record=state.progress[s.id];if(record&&record.answers.length){var list=el('ul','recap');record.answers.forEach(function(a){list.appendChild(el('li','',a));});root.appendChild(list);}root.appendChild(el('p','','Sprecht zu zweit: Welche Idee nehmt ihr mit?'));root.appendChild(button('Zurück zu den Stationen',function(){showRoom(s.room);},'btn sunshine'));root.appendChild(button('Noch einmal üben',replay,'btn ghost'));}
function orderFor(p,n){if(!Array.isArray(p.order)||p.order.length!==n||new Set(p.order).size!==n||p.order.some(function(v){return !Number.isInteger(v)||v<0||v>=n;})){p.order=C.choices(n,p.previous);save();}return p.order;}
function next(p){p.previous=p.order.indexOf(0);p.index++;p.order=[];p.errors=0;p.reply=null;p.penalized=false;save();}
function replyPanel(root,p,draw,onContinue,onGuided){if(!p.reply)return false;var text=el('p','feedback '+(p.reply.good?'good':'needs-help'),p.reply.text);text.setAttribute('role','status');root.appendChild(text);if(p.reply.good)root.appendChild(button(p.reply.end?'Station abschließen ✓':'Weiter →',onContinue,'btn sunshine'));else root.appendChild(button(p.errors>=2?'Hinweis gemeinsam anwenden':'Noch einmal überlegen',function(){if(p.errors>=2)onGuided();else{p.reply=null;save();draw();}},'btn sunshine'));return true;}
function markAnswer(p,text){p.answers[p.index]=text;}
function choicesUI(root,p,options,correct,explanation,draw,accept,wrong){var opts=el('div','options');root.appendChild(opts);orderFor(p,options.length).forEach(function(i){var b=button(options[i],function(){if(p.reply)return;if(i===correct)accept();else{p.errors++;var reason=wrong?wrong(i):null;p.reply={good:false,text:'Noch nicht ganz. '+(reason||explanation)};save();draw();}},'opt-btn');if(p.reply){b.disabled=true;if(i===correct&&p.errors>=2)b.classList.add('correct');}opts.appendChild(b);});}
function stage(s,p,root,total){var st=el('div','learning-stage stage-'+s.kind);st.setAttribute('aria-label','Fortschritt: '+p.index+' von '+total);var slots=el('div','stage-slots');for(var i=0;i<total;i++){var label=s.kind==='bridge'?'Brett '+(i+1):s.kind==='workshop'?['Beschreiben','Gefühle','Verantwortung','Handeln'][i]:s.kind==='lock'?'Riegel '+(i+1):'Fragment '+(i+1);slots.appendChild(el('span',i<p.index||(i===p.index&&p.reply&&p.reply.good)?'stage-piece fixed':'stage-piece',label));}st.appendChild(slots);root.appendChild(st);}
function quiz(s,p,root,draw){if(p.index>=s.steps.length){finish(s,p,root);return;}root.appendChild(el('p','round-count','Schritt '+(p.index+1)+' / '+s.steps.length));if(['tablet','bridge','workshop','lock'].includes(s.kind))stage(s,p,root,s.steps.length);var q=s.steps[p.index];root.appendChild(el('h3','question',q.prompt));function accept(){markAnswer(p,q.options[0]);p.reply={good:true,text:'✓ '+q.explanation,end:p.index===s.steps.length-1};save();draw();}choicesUI(root,p,q.options,0,q.hint,draw,accept);replyPanel(root,p,draw,function(){next(p);draw();},accept);}
function matching(s,p,root,draw){if(p.index>=s.cards.length){finish(s,p,root);return;}root.appendChild(el('p','round-count','Karte '+(p.index+1)+' / '+s.cards.length));var card=s.cards[p.index],board=el('div','match-board');board.appendChild(el('p','selected-card','📌 Diese Karte verbindet ihr: '+card.text));root.appendChild(board);var selected=s.buckets.find(function(b){return b.key===card.key;});var options=[selected.label].concat(s.buckets.filter(function(b){return b.key!==card.key;}).map(function(b){return b.label;}));function accept(){markAnswer(p,card.text+' → '+selected.label);p.reply={good:true,text:'✓ '+card.why,end:p.index===s.cards.length-1};save();draw();}choicesUI(root,p,options,0,'Achtet auf den Schwerpunkt. '+card.why,draw,accept);replyPanel(root,p,draw,function(){next(p);draw();},accept);var folded=el('details','placed-cards');folded.appendChild(el('summary','',p.answers.length+' Karten bereits verbunden'));p.answers.forEach(function(a){folded.appendChild(el('p','',a));});root.appendChild(folded);}
function worry(s,p,root,draw){if(!Array.isArray(p.deck)||p.deck.length!==6||new Set(p.deck).size!==6||p.deck.some(function(i){return !Number.isInteger(i)||i<0||i>=D.worries.length;})){p.deck=C.shuffle(D.worries.map(function(_,i){return i;})).slice(0,6);save();}
if(p.index>=6){if(p.burden>0){root.appendChild(el('h3','','Gemeinsam leichter weitergehen'));root.appendChild(el('p','feedback','Sechs Situationen sind geschafft. Noch '+p.burden+' Laststeine: Überlegt einen kleinen nächsten Schritt. Hilfe annehmen ist auch ein Erfolg.'));var supports=['Mit einer vertrauten Person reden','Eine Pause machen','Einen kleinen Schritt planen','Eine Grenze freundlich benennen','Um Unterstützung bitten'];root.appendChild(button(supports[p.burden-1]+' · einen Stein ablegen',function(){p.burden--;save();draw();},'btn sunshine'));return;}finish(s,p,root);return;}
var i=p.deck[p.index],q=D.worries[i];root.appendChild(el('p','round-count','Situation '+(p.index+1)+' · noch '+p.burden+(p.burden===1?' Laststein':' Laststeine')+' im Rucksack'));var scene=el('div','worry-scene compact-worry');scene.appendChild(el('p','jona-speech','Jona: „'+q.worry+'“'));var cast=el('div','worry-cast');var l=el('div','adviser-portrait');l.setAttribute('aria-label','Eine Person hört Jona zu.');cast.appendChild(l);var walker=el('div','worry-walker');walker.setAttribute('aria-hidden','true');var img=el('img','jona-person');img.src='assets/jona.png';img.alt='';walker.appendChild(img);var bag=el('div','worry-bag');bag.dataset.count=p.burden;bag.style.setProperty('--bag-scale',String(.55+p.burden*.14));var rocks=el('div','worry-rocks');for(var r=0;r<p.burden;r++)rocks.appendChild(el('span','worry-rock'));bag.appendChild(rocks);walker.appendChild(bag);cast.appendChild(walker);var right=el('div','adviser-portrait portrait-right');right.setAttribute('aria-label','Eine weitere Person bietet Rat an.');cast.appendChild(right);scene.appendChild(cast);root.appendChild(scene);
root.appendChild(el('h3','question','Welcher Rat hilft Jona hier am besten?'));function accept(){var hadStone=p.burden>0;p.burden=C.bag(p.burden,true);markAnswer(p,q.good);var empty=p.burden===0;p.reply={good:true,text:(empty?'✓ Der letzte Stein ist weg – Jonas Rucksack ist leer! ':hadStone?'✓ Ein Stein wird leichter. ':'✓ Ein hilfreicher Rat. ')+q.why,end:empty};save();draw();}
choicesUI(root,p,[q.good,q.bad,D.thirdAdvice[i]],0,q.why,draw,accept,function(choiceIndex){if(!p.penalized){p.burden=C.bag(p.burden,false);p.penalized=true;}return choiceIndex===2?D.thirdWhy[i]+' '+q.why:q.why;});replyPanel(root,p,draw,function(){if(p.burden===0){next(p);p.index=6;save();}else next(p);draw();},accept);}
function mountain(s,p,root,draw){if(!p.mode){root.appendChild(el('p','feedback','Entdecken: zehn Aussagen, ohne Zeitdruck und ohne Punktabzug. Herausforderung: Ein Fehler entfernt zwei Gravuren. Fehlende Teile ergänzen wir am Ende gemeinsam.'));['learn','challenge'].forEach(function(m){root.appendChild(button(m==='learn'?'Entdecken starten':'Herausforderung starten',function(){p.mode=m;p.deck=C.mountainDeck();save();draw();},m==='learn'?'btn sunshine':'btn ghost'));});return;}
if(!Array.isArray(p.deck)||p.deck.length!==10||new Set(p.deck.map(function(x){return x&&x.id;})).size!==10||p.deck.some(function(x){return !x||!Number.isInteger(x.id)||x.id<1||x.id>10;})){p.deck=C.mountainDeck();save();}
p.engraved=p.engraved.filter(function(n,i,a){return Number.isInteger(n)&&n>=1&&n<=10&&a.indexOf(n)===i;});
var complete=p.index>=10;if(complete&&p.engraved.length===10){finish(s,p,root);return;}var missing=D.commandments.filter(function(g){return !p.engraved.includes(g.id);}),g=complete?missing[0]:D.commandments[p.deck[p.index].id-1],item=complete?null:p.deck[p.index];root.appendChild(el('p','round-count',complete?'Gemeinsam ergänzen · '+p.engraved.length+' / 10 Gravuren':'Aussage '+(p.index+1)+' / 10 · '+p.engraved.length+' Gravuren · ohne Zeitdruck'));
var scene=el('div','mountain-scene compact-mountain');var speech=el('p','mountain-statement',complete?g.words[0]:(item.trueStatement?g.words[0]:D.mountainFalse[g.id-1]));scene.appendChild(speech);var controls=el('div','mountain-decisions');scene.appendChild(controls);root.appendChild(scene);
function accept(){if(!p.engraved.includes(g.id))p.engraved.push(g.id);markAnswer(p,g.id+' · '+g.label);p.reply={good:true,text:'✓ '+(item.trueStatement?'Diese Aussage passt. ':'Die Aussage war verfälscht. Richtig ist: '+g.words[0]+' ')+D.book[g.id-1].now};save();draw();}
if(complete){scene.appendChild(el('p','feedback',D.book[g.id-1].now));scene.appendChild(button('Dieses Gebot ergänzen',function(){p.engraved.push(g.id);save();draw();},'btn sunshine'));}else{['Passt zum Gebot ✓','Die Aussage stimmt nicht ✕'].forEach(function(label,i){var b=button(label,function(){if(p.reply)return;if((i===0)===item.trueStatement)accept();else{p.errors++;if(p.mode==='challenge'&&!p.penalized){p.engraved=C.removeTwo(p.engraved);p.penalized=true;}p.reply={good:false,text:'Lest den Unterschied: '+g.words[0]+' '+D.book[g.id-1].now};save();draw();}},'btn');b.disabled=!!p.reply;controls.appendChild(b);});replyPanel(scene,p,draw,function(){next(p);draw();},accept);}
var tablets=el('div','stone-tablets');for(var t=0;t<2;t++){var tablet=el('div','stone-tablet'),list=el('ol','engraved-list');list.start=t*5+1;for(var n=t*5+1;n<=t*5+5;n++)list.appendChild(el('li',p.engraved.includes(n)?'engraved':'empty',p.engraved.includes(n)?D.commandments[n-1].label:'Noch frei'));tablet.appendChild(list);tablets.appendChild(tablet);}scene.appendChild(tablets);}
function renderStation(s,p,root,draw){if(s.kind==='worry')worry(s,p,root,draw);else if(s.kind==='mountain')mountain(s,p,root,draw);else if(s.kind==='match')matching(s,p,root,draw);else quiz(s,p,root,draw);}
window.KapelleHost={get state(){return state;},save:save,required:required,screen:screen,dialog:dialog,el:el,button:button,focusHeading:focusHeading,refresh:refresh,book:book};
save();screen('intro');
})();
